### PR TITLE
Browser: remove use of deprecated widgets

### PR DESCRIPTION
**Pull request by benwaffle**

### CODE REVIEW

**Comment by WebReflection** [comment]
Very interesting. Do you know how to trigger eventually deprecation warnings?

**Comment by benwaffle** [comment]
https://developer.gnome.org/gi/stable/gi-GIBaseInfo.html#g-base-info-is-deprecated

**Comment by magcius** [comment]
From my experience with Python, the main issue with runtime deprecation warnings is that it punishes users (outputting something that looks like an error), and not developers.

**Comment by WebReflection** [comment]
agreed @magcius I was rather thinking to enable it only via `npm run install --debug` builds but right now I guess that's the very last problem we have.

Please have a look into other bits and bops I've pushed and written today, thanks :-)

**Pull request merged**
